# This is a basic workflow to help you get started with Actions

name: pr-collector

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pr_collector:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pr_number: ${{ join(needs.get_pr_numbers.outputs.pr_numbers, ',') }}

    steps:
    # Add your desired steps here
    - name: Step 1
      run: echo "Running Step 1 for PR ${{ matrix.pr_number }}"
#jobs:
  #your_job_name:
    #runs-on: ubuntu-latest

    #steps:
    # Add your desired steps here
    #- name: Step 1
    #  run: echo "Running Step 1 - ${{ github.event.pull_request.title }}"
