name: Get PR Numbers

on:
  schedule:
    - cron: '*/5 * * * *' # Runs at midnight (00:00) every day
  workflow_dispatch:

jobs:
  get_pr_numbers:
    runs-on: ubuntu-latest

    steps:
    - name: Get Open PR Numbers
      id: get_pr_numbers
      run: |
        pr_numbers=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r '.[].number')
        echo "::set-output name=pr_numbers::${pr_numbers}"
        echo "${pr_numbers}"
